#ifndef TL_CONFIG_H
#define TL_CONFIG_H
#include "TL_Device_ID.h"
#define PLATFORM 1
#define BOARD 1002
#define TINYLINK_SERIAL ONE_SERIAL
#define TINYLINK_TIME ONE_TIME
#define TINYLINK_LIGHT GROVE_LIGHT
#define TINYLINK_TEMPERATURE GROVE_TEMPERATURE
#define TINYLINK_HTTP ONE_HTTP
#define TINYLINK_WIFI ONE_WIFI
#define TINYLINK_ULTRASONIC ONE_ULTRASONIC  // add ultrasonic range 
#define TINYLINK_PM25 SDS018
#define TEMPERATURE_ANALOG A2
#define LIGHT_ANALOG A0
#endif
